title: "Your Name - Portfolio"  # Change this
description: "Electrical Engineering Portfolio"
baseurl: "/online-cv"  # Critical for project sites!
remote_theme: pages-themes/minimal@v0.2.0
plugins:
  - jekyll-remote-theme
